stages:
  - build

build:
  stage: build
  image: 10.240.34.2:10000/cibuilder/xilinx-vitis:v1
  tags:
    - vitis
  only:
    refs:
      - branches
      - merge_requests
      - tags
  script:
    - if [[ -n "$CI_COMMIT_TAG" ]];then VERSION="$CI_COMMIT_TAG"; elif [[ -z "$VERSION" ]];then VERSION="V99.99.99"; fi
    - bash 01_code/build/build_ci.sh $VERSION
  artifacts:
    paths:
      - 01_code/build/release*
    expire_in: 2 weeks
