
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiic.h"

/*
* The configuration table for devices
*/

XIic_Config XIic_ConfigTable[XPAR_XIIC_NUM_INSTANCES] =
{
	{
		XPAR_BAT_I2C_DEVICE_ID,
		XPAR_BAT_I2C_BASEADDR,
		XPAR_BAT_I2C_TEN_BIT_ADR,
		XPAR_BAT_I2C_GPO_WIDTH
	},
	{
		XPAR_PL_I2C0_DEVICE_ID,
		XPAR_PL_I2C0_BASEADDR,
		XPAR_PL_I2C0_TEN_BIT_ADR,
		XPAR_PL_I2C0_GPO_WIDTH
	}
};


